export default [
  {title: 'Action', value: 'action'},
  {title: 'Adventure', value: 'adventure'},
  {title: 'Animation', value: 'animation'},
  {title: 'Comedy', value: 'comedy'},
  {title: 'Crime', value: 'crime'},
  {title: 'Documentary', value: 'documentary'},
  {title: 'Drama', value: 'drama'},
  {title: 'Family', value: 'family'},
  {title: 'Fantasy', value: 'fantasy'},
  {title: 'History', value: 'history'},
  {title: 'Horror', value: 'horror'},
  {title: 'Music', value: 'music'},
  {title: 'Mystery', value: 'mystery'},
  {title: 'Romance', value: 'romance'},
  {title: 'Sci-Fi', value: 'sci-fi'},
  {title: 'Sport', value: 'sport'},
  {title: 'Thriller', value: 'thriller'},
  {title: 'War', value: 'war'},
  {title: 'Western', value: 'western'},
]
